spring:
  application:
    name: jp-another-ms

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
logging:
  file:
    name: demo.log